Update source

diff --git a/gforthp.in b/gforthp.in
--- a/gforthp.in
+++ b/gforthp.in
@@ -1,7 +1,7 @@
 #!/bin/sh
 
 #Authors: Bernd Paysan, Anton Ertl
-#Copyright (C) 2008,2011,2012,2016,2017,2018,2019,2023 Free Software Foundation, Inc.
+#Copyright (C) 2008,2011,2012,2016,2017,2018,2019,2023,2024 Free Software Foundation, Inc.
 
 #This file is part of Gforth.
 
@@ -32,7 +32,7 @@ else
     export C_INCLUDE_PATH="@srcdir@/include/gforth/$VERSION/$machine:@srcdir@/engine"
 fi
 if test -f "$ENGINE" -a -f "$KERNEL"; then 
-  $ENGINE --die-on-signal "$@" || (printf "\e[31m*** Gforth kernel failed ***\e[0m\n"; exit 1) >&2
+  $ENGINE --die-on-signal=2 "$@" || (printf "\e[31m*** Gforth kernel failed ***\e[0m\n"; exit 1) >&2
 else
     @GFORTH@ "$@" || (printf "\e[31m*** Gforth kernel failed ***\e[0m\n"; exit 1) >&2
 fi
